### ISSUE TITLE
System.BadImageFormatException during tampering deobfuscation

### ISSUE THREAD

**Issue by GrimSmiler** [CodeShark-Dev/NoFuserEx#12]
hey!

when trying to run this command:
`.\NoFuserEx.exe "AE.Net.Mail.dll" --dont-constants --dont-cflow --dont-proxy-calls --dont-remove-junk-methods --dont-resources --dont-rename`

I get the following  error:
```
Unhandled Exception: System.BadImageFormatException: Invalid IMAGE_COR20_HEADER.cb value
   at dnlib.DotNet.MD.ImageCor20Header..ctor(IImageStream reader, Boolean verify) in D:\THESIS\98-Deobfuscation\NoFuserEx-master\NoFuserEx-master\dnlib\src\DotNet\MD\ImageCor20Header.cs:line 127
   at dnlib.DotNet.MD.MetaDataCreator.Create(IPEImage peImage, Boolean verify) in D:\THESIS\98-Deobfuscation\NoFuserEx-master\NoFuserEx-master\dnlib\src\DotNet\MD\MetaDataCreator.cs:line 176
   at dnlib.DotNet.MD.MetaDataCreator.Load(IPEImage peImage) in D:\THESIS\98-Deobfuscation\NoFuserEx-master\NoFuserEx-master\dnlib\src\DotNet\MD\MetaDataCreator.cs:line 105
   at dnlib.DotNet.MD.MetaDataCreator.Load(Byte[] data) in D:\THESIS\98-Deobfuscation\NoFuserEx-master\NoFuserEx-master\dnlib\src\DotNet\MD\MetaDataCreator.cs:line 49
   at dnlib.DotNet.ModuleDefMD.Load(Byte[] data, ModuleCreationOptions options) in D:\THESIS\98-Deobfuscation\NoFuserEx-master\NoFuserEx-master\dnlib\src\DotNet\ModuleDefMD.cs:line 188
   at NoFuserEx.Deobfuscator.Deobfuscators.AntiTamperDeobfuscator.Deobfuscate(AssemblyManager assemblyManager) in D:\THESIS\98-Deobfuscation\NoFuserEx-master\NoFuserEx-master\NoFuserEx\NoFuserEx\Deobfuscator\Deobfuscators\AntiTamperDeobfuscator.cs:line 47
   at NoFuserEx.Deobfuscator.DeobfuscatorManager.Start() in D:\THESIS\98-Deobfuscation\NoFuserEx-master\NoFuserEx-master\NoFuserEx\NoFuserEx\Deobfuscator\DeobfuscatorManager.cs:line 57
   at NoFuserEx.Program.Main(String[] args) in D:\THESIS\98-Deobfuscation\NoFuserEx-master\NoFuserEx-master\NoFuserEx\NoFuserEx\Program.cs:line 28
```

The obfuscations applied to the dll are the following:

- constants
- ref proxy
- anti debug
- anti dump
- rename
- ctrl flow
- anti tamper

I attached the project file for the ConfuserEx, original and obfuscated dlls
[bug.zip](https://github.com/CodeShark-Dev/NoFuserEx/files/655433/bug.zip)

What could be the cause of this and what can be done to fix this issue?

**Comment by undebel** [comment]
It has anti dump and anti tamper, it is not supported.

**Comment by thquantv1** [comment]
any idea for that error? or any solution?

**Comment by thquantv1** [comment]
![untitled](https://user-images.githubusercontent.com/18158148/31934873-85021026-b8d7-11e7-85f4-72d0ca9510b7.png)

**Comment by GrimSmiler** [comment]
No idea.

For me the problem was that anti-tampering and anti-obfuscation was applied and that forbids the restoring of the assembly.

Couldn't fix it

Sent from Blue<http://www.bluemail.me/r?b=10777>
On Oct 24, 2017, at 11:22 AM, thquantv1 <notifications@github.com<mailto:notifications@github.com>> wrote:

[untitled]<https://user-images.githubusercontent.com/18158148/31934873-85021026-b8d7-11e7-85f4-72d0ca9510b7.png>

**Comment by thquantv1** [comment]
any way to change title of Main Form 
I need to change some label text 
Try with Pe Explorer(only logo and description) and OllyDBG(can not open) but not

**Comment by yanghoxom** [comment]
i see in readme support Anti-tamper and Anti-dumper. but in this issues, you say no ?
